export const carDetails = [
  {
    id: "Hb20",
    marca: "Hyundai",
    modelo: "HB20",
    year: 2023,
    power: "1.6",
    doors: 4,
    fuel: "Flex",
    transmission: "Manual",
    price: "R$ 2.000,00/mês*",
    plan: "Plano de 1 mês",
    image: "/cars/hb20.webp",
    subInfo: "HB20 1.6 FLEX AUT",
  },
  {
    id: "Kwid",
    marca: "Renault",
    modelo: "Kwid",
    year: 2022,
    power: "1.0",
    doors: 4,
    fuel: "Flex",
    transmission: "Manual",
    price: "R$ 2.000,00/mês*",
    plan: "Plano de 1 mês",
    image: "/cars/kwid.png",
    subInfo: "KWID 1.0 FLEX MAN",
  },
  {
    id: "Onix",
    marca: "Chevrolet",
    modelo: "Onix",
    year: 2023,
    power: "1.0 Turbo",
    doors: 4,
    fuel: "Flex",
    transmission: "Automático",
    price: "R$ 2.000,00/mês*",
    plan: "Plano de 1 mês",
    image: "/cars/onix.png",
    subInfo: "ONIX 1.0 TURBO FLEX AUT",
  },
  {
    id: "Gol",
    marca: "Volkswagen",
    modelo: "Gol",
    year: 2021,
    power: "1.6",
    doors: 4,
    fuel: "Flex",
    transmission: "Manual",
    price: "R$ 2.000,00/mês*",
    plan: "Plano de 1 mês",
    image: "/cars/gol.png",
    subInfo: "GOL 1.6 FLEX MAN",
  },
  {
    id: "Uno",
    marca: "Fiat",
    modelo: "Uno",
    year: 2019,
    power: "1.0",
    doors: 4,
    fuel: "Flex",
    transmission: "Manual",
    price: "R$ 2.000,00/mês*",
    plan: "Plano de 1 mês",
    image: "/cars/uno.png",
    subInfo: "UNO 1.0 FLEX MAN",
  },
  {
    id: "Palio",
    marca: "Fiat",
    modelo: "Palio",
    year: 2017,
    power: "1.4",
    doors: 4,
    fuel: "Flex",
    transmission: "Manual",
    price: "R$ 2.000,00/mês*",
    plan: "Plano de 1 mês",
    image: "/cars/palio.png",
    subInfo: "PALIO 1.4 FLEX MAN",
  },
  {
    id: "Mobi",
    marca: "Fiat",
    modelo: "Mobi",
    year: 2023,
    power: "1.0",
    doors: 4,
    fuel: "Flex",
    transmission: "Manual",
    price: "R$ 2.000,00/mês*",
    plan: "Plano de 1 mês",
    image: "/cars/mobi.webp",
    subInfo: "MOBI 1.0 FLEX MAN",
  },
  {
    id: "Prisma",
    marca: "Chevrolet",
    modelo: "Prisma",
    year: 2018,
    power: "1.4",
    doors: 4,
    fuel: "Flex",
    transmission: "Automático",
    price: "R$ 2.000,00/mês*",
    plan: "Plano de 1 mês",
    image: "/cars/prisma.png",
    subInfo: "PRISMA 1.4 FLEX AUT",
  },
  {
    id: "Voyage",
    marca: "Volkswagen",
    modelo: "Voyage",
    year: 2020,
    power: "1.6",
    doors: 4,
    fuel: "Flex",
    transmission: "Manual",
    price: "R$ 2.000,00/mês*",
    plan: "Plano de 1 mês",
    image: "/cars/voyage.webp",
    subInfo: "VOYAGE 1.6 FLEX MAN",
  },
  {
    id: "Sandero",
    marca: "Renault",
    modelo: "Sandero",
    year: 2022,
    power: "1.6",
    doors: 4,
    fuel: "Flex",
    transmission: "Automático",
    price: "R$ 2.000,00/mês*",
    plan: "Plano de 1 mês",
    image: "/cars/sandero.webp",
    subInfo: "SANDERO 1.6 FLEX AUT",
  },
  {
    id: "Citroen",
    marca: "Citroën",
    modelo: "C3",
    year: 2023,
    power: "1.6",
    doors: 4,
    fuel: "Flex",
    transmission: "Automático",
    price: "R$ 2.000,00/mês*",
    plan: "Plano de 1 mês",
    image: "/cars/c3.webp",
    subInfo: "C3 1.6 FLEX AUT",
  },
  {
    id: "Yaris",
    marca: "Toyota",
    modelo: "Yaris",
    year: 2023,
    power: "1.5",
    doors: 4,
    fuel: "Flex",
    transmission: "Automático",
    price: "R$ 2.000,00/mês*",
    plan: "Plano de 1 mês",
    image: "/cars/yaris.webp",
    subInfo: "YARIS 1.5 FLEX AUT",
  },
  {
    id: "March",
    marca: "Nissan",
    modelo: "March",
    year: 2020,
    power: "1.0",
    doors: 4,
    fuel: "Flex",
    transmission: "Manual",
    price: "R$ 2.000,00/mês*",
    plan: "Plano de 1 mês",
    image: "/cars/march.webp",
    subInfo: "MARCH 1.0 FLEX MAN",
  },
  {
    id: "Fit",
    marca: "Honda",
    modelo: "Fit",
    year: 2019,
    power: "1.5",
    doors: 4,
    fuel: "Flex",
    transmission: "CVT (Automático)",
    price: "R$ 2.000,00/mês*",
    plan: "Plano de 1 mês",
    image: "/cars/fit.png",
    subInfo: "FIT 1.5 FLEX CVT",
  },
  {
    id: "Peugeot",
    marca: "Peugeot",
    modelo: "208",
    year: 2023,
    power: "1.6",
    doors: 4,
    fuel: "Flex",
    transmission: "Automático",
    price: "R$ 2.000,00/mês*",
    plan: "Plano de 1 mês",
    image: "/cars/208.webp",
    subInfo: "208 1.6 FLEX AUT",
  },
];